name: Run Kotlin examples

on:
  workflow_dispatch:
  schedule:
    - cron: '45 22 * * *'
  pull_request:
    branches:
      - trunk
    paths:
      - 'examples/kotlin/**'
  push:
    branches:
      - trunk
    paths:
      - 'examples/kotlin/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Run tests
      uses: nick-invision/retry@v2.8.3
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: |
          cd examples/kotlin
          mvn -B test
